FROM mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04

USER root

RUN apt-get update && \
    apt-get clean

RUN apt-get install -y git nano sudo

RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y aspnetcore-runtime-3.1

COPY ./Chat ./Chat