version: '3'


volumes:
  db-data:

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
    - "5000:1433"

  dotnet:
    image: fros/dotnet-efapp

    depends_on:
      - db
