FROM ubuntu:20.04

USER root

RUN apt-get update && \
    apt-get clean

RUN apt-get install -y git nano sudo

RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb

#RUN apt-get install -y aspnetcore-runtime-3.1
RUN apt-get install -y dotnet-sdk-3.1
RUN apt-get update

#COPY ./Chat ./Chat
#COPY ./Chess ./Chess
#ENTRYPOINT ["dotnet","App.dll"]